# See http://about.travis-ci.org/docs/user/build-configuration/

language: scala

scala:
  - 2.11.6
  - 2.11.7
  - 2.11.8
  - 2.12.0
  - 2.12.1
  - 2.12.2
  - 2.12.3
  - 2.12.4
  - 2.13.0

jdk:
  - oraclejdk8
